# Generated by Django 3.2.9 on 2021-12-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcase', '0003_auto_20211207_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='organization_id',
        ),
    ]
