# Generated by Django 3.2.9 on 2021-12-06 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcase', '0005_remove_transactions_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subcase.users'),
        ),
    ]
