# Generated by Django 3.2.9 on 2021-12-06 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcase', '0006_transactions_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='subcase.users'),
        ),
    ]
